# Generated by Django 2.1 on 2020-02-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Creator', models.CharField(max_length=20)),
                ('SongName', models.CharField(max_length=10)),
                ('Lyricist', models.CharField(max_length=10)),
                ('Compose', models.CharField(max_length=10)),
                ('Singer', models.CharField(max_length=10)),
                ('Type', models.CharField(max_length=10)),
                ('CopyRight', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=10)),
                ('SingDate', models.CharField(max_length=20)),
                ('Accompany', models.CharField(max_length=20)),
                ('CoverImage', models.ImageField(null=True, upload_to='audio', verbose_name='图片')),
                ('Lyrics', models.TextField()),
                ('SingerIntro', models.TextField()),
                ('SongIntro', models.TextField()),
                ('Tag', models.CharField(max_length=20)),
                ('MusciPath', models.FileField(blank=True, upload_to='audio')),
            ],
        ),
    ]
