# Generated by Django 2.1 on 2020-02-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfyage_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='Compose',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='audio',
            name='Lyricist',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
